name: Recreate repo

on:
  workflow_dispatch:
    inputs:
      candidate_username:
        description: 'Candidate GitHub Username'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Install Dependencies
        run: npm install

      - name: Check if GITHUB_TOKEN is available
        run: |
          if [ -z "${{ secrets.MY_PERSONAL_TOKEN }}" ]; then
            echo "MY_PERSONAL_TOKEN is not set"
          else
            echo "MY_PERSONAL_TOKEN is set"
          fi

      - name: Run Script
        env:
          CANDIDATE_GITHUB_USERNAME: ${{ github.event.inputs.candidate_username }}
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }} # Using your personal access token
        run: node re-create.js
